// @generated by scripts/gen-dispatch-data.mjs from src/core/events.ts — DO NOT EDIT.
// Run `npm run build` to regenerate after changing the event registry or locales.
export const DISPATCH_DATA = {
  events: {
    Notification: {
      configKey: "notification",
      defaultEnabled: true,
      verbose: false,
      sound: "Notification.Default",
      resolver: "notification",
      scenario: null,
    },
    Stop: {
      configKey: "stop",
      defaultEnabled: true,
      verbose: false,
      sound: "Notification.IM",
      resolver: null,
      scenario: null,
    },
    StopFailure: {
      configKey: "stopFailure",
      defaultEnabled: true,
      verbose: false,
      sound: "Notification.Looping.Alarm2",
      resolver: "stopFailure",
      scenario: null,
    },
    SubagentStop: {
      configKey: "subagentStop",
      defaultEnabled: false,
      verbose: false,
      sound: "Notification.IM",
      resolver: "agentNamed",
      scenario: null,
    },
    SubagentStart: {
      configKey: "subagentStart",
      defaultEnabled: false,
      verbose: true,
      sound: "Notification.IM",
      resolver: "agentNamed",
      scenario: null,
    },
    TaskCreated: {
      configKey: "taskCreated",
      defaultEnabled: false,
      verbose: true,
      sound: "Notification.IM",
      resolver: "taskNamed",
      scenario: null,
    },
    TaskCompleted: {
      configKey: "taskCompleted",
      defaultEnabled: false,
      verbose: true,
      sound: "Notification.IM",
      resolver: "taskNamed",
      scenario: null,
    },
    PreCompact: {
      configKey: "preCompact",
      defaultEnabled: false,
      verbose: true,
      sound: "Notification.Reminder",
      resolver: "compact",
      scenario: "reminder",
    },
    PostCompact: {
      configKey: "postCompact",
      defaultEnabled: false,
      verbose: true,
      sound: "Notification.Reminder",
      resolver: "compact",
      scenario: null,
    },
  },
  translations: {
    "pt-BR": {
      Notification: {
        title: "Claude Code — Atenção necessária",
        body: "Claude Code precisa da sua atenção",
      },
      Stop: {
        title: "Claude Code — Tarefa concluída",
        body: "Aguardando próximo input",
      },
      StopFailure: {
        title: "Claude Code — Erro de API",
        body: "A sessão foi encerrada por um erro (rate limit, billing, auth, etc)",
      },
      SubagentStop: {
        title: "Claude Code — Subagent finalizado",
        body: "Um subagent terminou",
      },
      SubagentStart: {
        title: "Claude Code — Subagent iniciado",
        body: "Um subagent começou a trabalhar",
      },
      TaskCreated: {
        title: "Claude Code — Tarefa criada",
        body: "Uma nova tarefa foi criada",
      },
      TaskCompleted: {
        title: "Claude Code — Tarefa concluída",
        body: "Uma tarefa foi concluída",
      },
      PreCompact: {
        title: "Claude Code — Compactando contexto",
        body: "O histórico da conversa está sendo compactado",
      },
      PostCompact: {
        title: "Claude Code — Contexto compactado",
        body: "O histórico da conversa foi compactado",
      },
    },
    "en-US": {
      Notification: {
        title: "Claude Code — Attention required",
        body: "Claude Code needs your attention",
      },
      Stop: {
        title: "Claude Code — Task complete",
        body: "Waiting for your next input",
      },
      StopFailure: {
        title: "Claude Code — API error",
        body: "The session ended with an error (rate limit, billing, auth, etc.)",
      },
      SubagentStop: {
        title: "Claude Code — Subagent finished",
        body: "A subagent finished",
      },
      SubagentStart: {
        title: "Claude Code — Subagent started",
        body: "A subagent started working",
      },
      TaskCreated: {
        title: "Claude Code — Task created",
        body: "A new task was created",
      },
      TaskCompleted: {
        title: "Claude Code — Task completed",
        body: "A task was completed",
      },
      PreCompact: {
        title: "Claude Code — Compacting context",
        body: "The conversation history is being compacted",
      },
      PostCompact: {
        title: "Claude Code — Context compacted",
        body: "The conversation history was compacted",
      },
    },
  },
  errorTypes: {
    "pt-BR": {
      rate_limit: "Limite de uso atingido — aguarde o reset da sua cota",
      authentication_failed: "Falha de autenticação — sua sessão expirou ou o token está inválido",
      oauth_org_not_allowed: "Organização não autorizada a usar esta conta",
      billing_error: "Erro de cobrança — verifique seu plano e método de pagamento",
      invalid_request: "Requisição inválida enviada à API",
      model_not_found: "Modelo selecionado não encontrado ou indisponível",
      server_error: "Erro no servidor da Anthropic — tente novamente em instantes",
      max_output_tokens: "Limite de tokens de saída atingido nesta resposta",
      unknown: "Erro desconhecido encerrou a sessão",
    },
    "en-US": {
      rate_limit: "Usage limit reached — wait for your quota to reset",
      authentication_failed: "Authentication failed — your session expired or the token is invalid",
      oauth_org_not_allowed: "Organization not allowed to use this account",
      billing_error: "Billing error — check your plan and payment method",
      invalid_request: "Invalid request sent to the API",
      model_not_found: "Selected model not found or unavailable",
      server_error: "Anthropic server error — try again in a moment",
      max_output_tokens: "Output token limit reached for this response",
      unknown: "Unknown error ended the session",
    },
  },
  notificationTypes: {
    "pt-BR": {
      permission_prompt: "Permissão necessária para executar uma ferramenta",
      idle_prompt: "Aguardando sua resposta",
      auth_success: "Autenticação concluída com sucesso",
      elicitation_dialog: "Servidor MCP solicitando informação",
      elicitation_complete: "Solicitação do servidor MCP concluída",
      elicitation_response: "Resposta enviada ao servidor MCP",
    },
    "en-US": {
      permission_prompt: "Permission required to run a tool",
      idle_prompt: "Waiting for your response",
      auth_success: "Authentication succeeded",
      elicitation_dialog: "MCP server is requesting information",
      elicitation_complete: "MCP server request completed",
      elicitation_response: "Response sent to MCP server",
    },
  },
};
